## Settings for the ManySinglets example.

[Grid]
# Specify sizes of our polynomials grid. See eq. (34) in 2204.13120
# M in the paper
spatialGridSize = 30

# N in the paper
# MUST BE ODD
momentumGridSize = 11

# Fraction of grid points inside the wall defined by the interval
# [-wallThickness+wallCenter, wallThickness+wallCenter] 
# (see the parameters of Grid3Scales).
# Should be a number between 0 and 1.
ratioPointsWall = 0.5

# Smoothing factor of the mapping function (the larger the smoother)
smoothing = 0.1

[EquationOfMotion]
# The absolute error tolerance for the wall-velocity result
errTol = 1e-3

# The parameters for finding the pressure on the wall at a given wall velocity
# in the file src/WallGo/equationOfMotion.py
# Relative error tolerance for the pressure
pressRelErrTol = 0.1

# Maximum number of iterations for the convergence of the pressure
maxIterations = 20

# Flag to enforce conservation of energy and momentum. 
# If True, it is enforced. If False, it is not.
# Normally, this should be set to True, but it can help with numerical stability
# to set it to False. If True, there is an ambiguity in the separation between
# f_{eq} and \delta f when the out-of-equilibrium particles form a closed 
# system (or nearly closed). This can lead to a divergence of the iterative loop.
conserveEnergyMomentum = True

# If True, uses a slower algorithm that improves the convergence when
# computing the pressure for deflagrations. Default is False. The improved
# algorithm is always used for detonations.
forceImproveConvergence = False

# Bounds on wall thickness (in units of 1/Tnucl)
wallThicknessLowerBound = 0.1
wallThicknessUpperBound = 100.0

# Bounds on wall offset (in units of the corresponding wall widths)
wallOffsetLowerBound = -10.0
wallOffsetUpperBound = 10.0

## The following parameters are only used for detonation solutions ##

# Maximal velocity at which the solver will look to find a detonation solution
vwMaxDeton = 0.99

# Mininal and maximal number of points probed to bracket the detonation roots
nbrPointsMinDeton = 5
nbrPointsMaxDeton = 20

# Desired probability of overshooting a root. Must be between 0 and 1.
# A smaller value will lead to more pressure evaluations (and thus a longer time), but
# is less likely to miss a root.
overshootProbDeton = 0.05

[Hydrodynamics]
# The following two parameters set the minimum and maximum temperature that is
# probed in Hydrodynamics. They are given in units of the nucleation temperature
tmin = 0.01
tmax = 10.

# Relative and absolute tolerance used in Hydrodynamics
relativeTol = 1e-6
absoluteTol = 1e-10

[Thermodynamics]
# The following two parameters set the minimum and maximum temperature that is
# used in the phase tracing. They are given in units of the estimates for the 
# minimum and maximum temperature obtained in the template model.
tmin = 0.8
tmax = 1.2

# Desired accuracy of the phase tracer and the resulting FreeEnergy interpolation.
phaseTracerTol = 1e-6

# First step size in units of the maximum step size. Use None for default algorithm.
phaseTracerFirstStep = None

# Degree of the splines used in FreeEnergy to interpolate the potential and its derivatives.
interpolationDegree = 1

[BoltzmannSolver]
# Factor multiplying the collision term in the Boltzmann equation.
# Can be used for testing or for studying the solution's sensibility
# to the collision integrals. Don't forget to adjust meanFreePath
# accordingly if this is different from 1 (meanFreePath ~ 1/collisionMultiplier).
# WARNING: THIS CHANGES THE COLLISION TERMS WRT TO THEIR PHYSICAL VALUE
collisionMultiplier = 1.0

# The position polynomial basis type, either Cardinal or Chebyshev.
basisM = Cardinal

# The momentum polynomial basis type, either Cardinal or Chebyshev.
basisN = Chebyshev

# Whether or not to truncate the spectral expansion
truncationOption = AUTO
